wso2/docs-ob-toolkit-uk

- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/configuring-api-manager-for-ob.md
- en/docs/install-and-setup/configuring-identity-server-for-ob.md
- en/docs/install-and-setup/configuring-users-and-roles.md
- en/docs/install-and-setup/prerequisites.md
- en/docs/install-and-setup/setting-up-databases.md
- en/docs/install-and-setup/setting-up-servers.md
- en/mkdocs.yml
Add the following topics as per the [developer doc draft](https://docs.google.com/document/d/1rvvsBaSIOM4JKX3H3POCQjCJC0O4vWeP5icxApJMrJU/edit#).
- Prerequisites
- Setting up servers
- Setting up databases
- Configuring Identity Server
- Configuring API Manager
- Configuring Users and Roles
> Add Install and setup

- en/docs/get-started/try-out-flow.md
- en/docs/try-out/dynamic-client-regsitration-flow.md
- Add config summary table for API publishing
- Add common page for API publishing 
- Link to OB3.0 webinar from the homepage
> Add steps to publish APIs

- en/docs/assets/js/theme.js
This PR is to update the script that loads previous product versions.
> Remove previous versions

- en/theme/material/main.html
This PR is to Remove OB Accelerator Algolia configs as we need to request new keys for the UK Toolkit.
> Remove Algolia configs

- en/mkdocs.yml
- en/theme/material/partials/header.html
This PR is to remove the WIP label and empty "References" tab
> Remove WIP label

- en/docs/install-and-setup/upgrading-the-solution/reporting-data-migration.md
- en/docs/install-and-setup/upgrading-the-solution/upgrading-the-solution.md
- en/docs/install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md
- en/docs/install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md
This PR is to update the Migration docs.
- Fix https://github.com/wso2/docs-open-banking/issues/548#issuecomment-1125707064. 
- Add steps to configure deployment.toml files.
> Update Migration Docs

- en/docs/install-and-setup/upgrading-the-solution/modifications-after-migration.md
This PR is to fix the port no of IS.
> Fix IS port number

- en/docs/learn/variable-recurring-payments.md
- en/mkdocs.yml
This PR is to add the intro page for VRP. This will fix https://github.com/wso2/docs-open-banking/issues/579
> Add VRP intro

- en/docs/get-started/open-banking-requirements.md
- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/prerequisites.md
- en/docs/install-and-setup/setting-up-servers.md
- en/docs/install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md
- en/docs/install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md
- en/docs/learn/app-to-app-redirection.md
- en/docs/learn/strong-customer-authentication.md
- en/docs/learn/token-authentication.md
- en/docs/try-out/account-and-transaction-flow.md
- en/docs/try-out/confirmation-of-funds-flow.md
- en/docs/try-out/payment-initiation-flow.md
- en/docs/try-out/variable-recurring-payments-flow.md
This PR does the following:
- Update IS and APIM doc links from `/latest/` to `/5.11.0/`
- Update base product download links from `/latest/` to `/4.0.0/`
- Fix a broken link.
> Update IS and APIM links

- en/docs/learn/api-security.md
This PR is to update the API security page with a list of security features available at each request type.
> Update API Security page

- en/docs/get-started/try-out-flow.md
- en/docs/try-out/account-and-transaction-flow.md
- en/docs/try-out/confirmation-of-funds-flow.md
- en/docs/try-out/payment-initiation-flow.md
Update the following pages, according to https://github.com/wso2/docs-open-banking/issues/590
- https://uk.ob.docs.wso2.com/en/latest/get-started/try-out-flow/
- https://uk.ob.docs.wso2.com/en/latest/try-out/account-and-transaction-flow/
- https://uk.ob.docs.wso2.com/en/latest/try-out/payment-initiation-flow/
- https://uk.ob.docs.wso2.com/en/latest/try-out/confirmation-of-funds-flow/
> Add steps to configure the Context field 

- en/docs/learn/api-security.md
To address https://github.com/wso2/docs-open-banking/pull/601#discussion_r913407490.
> Update FAPI intro

- en/theme/material/partials/footer.html
This PR is to update the footer note as follows
> Update copyright note to WSO2 LLC

- en/docs/install-and-setup/upgrading-the-solution/reporting-data-migration.md
> Update toolkit reference

- en/docs/learn/data-publishing-reports.md
This PR is to update Template 7 - PSU Consent Adoption on Generating Reports page according to https://docs.google.com/document/d/1SNaTqFa5yvZEJuRolkj0Ugv3_B8dJW4_Wxmj3Hw1pUU/edit#.
This will fix [#532](https://github.com/wso2/docs-open-banking/issues/532).
> Update Template 7 - PSU Consent Adoption

- en/docs/install-and-setup/configuring-identity-server-for-ob.md
This PR will fix  https://github.com/wso2/docs-open-banking/issues/629 with the following instructions in the https://uk.ob.docs.wso2.com/en/latest/install-and-setup/configuring-identity-server-for-ob/ page.
> Add config for token renewal

- en/docs/install-and-setup/configuring-api-manager-for-ob.md
- en/docs/install-and-setup/configuring-identity-server-for-ob.md
This PR is to add $subject according to the following: 
UK Open Banking JWS Signature Validation- https://docs.google.com/document/d/1wLhkNoc90ZeslA2ZioahBpqti47Ex35A3JE7hnYY8s4/edit?usp=sharing
UK Open Banking Response Signing - https://docs.google.com/document/d/1kDQPTTP6KfhRX65lMV6G82_46470418ltSD3zjeNIf8/edit?usp=sharing
Related to https://github.com/wso2/docs-open-banking/issues/651
> Add JWKS Signature Validation and Response Signing Conf

- en/docs/learn/integration-with-bank.md
This PR is to fix formatting issues in [Integration With Core Banking System](https://uk.ob.docs.wso2.com/en/latest/learn/integration-with-bank/).
> Fix formatting issues

- en/docs/get-started/open-banking-requirements.md
- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/prerequisites.md
- en/docs/install-and-setup/setting-up-servers.md
- en/docs/learn/dynamic-client-registration-configuration.md
- en/docs/learn/token-authentication.md
- en/docs/try-out/payment-initiation-flow.md
- en/docs/try-out/variable-recurring-payments-flow.md
This PR is to update UK Toolkit docs with APIM 4.1 version. 
This is to fix https://github.com/wso2/docs-open-banking/issues/689.
> Update the docs with APIM 4.1 version

- en/docs/install-and-setup/upgrading-the-solution/open-banking-data-migration.md
This is to fix https://github.com/wso2/docs-open-banking/issues/698.
> Remove links to migration tool

- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/setting-up-servers.md
This PR is to update the links to download the IS Connector.
This will fix https://github.com/wso2/docs-open-banking/issues/730.
> Update IS connector links

- en/docs/learn/dynamic-client-registration.md
This PR is to update the link to DCR API page.
> Update DCR API link

- en/docs/assets/attachments/scp-swagger.yaml
This PR is to update the scp-swagger.yaml file.
This will fix https://github.com/wso2/docs-open-banking/issues/780.
> Update the scp-swagger.yaml file

- en/docs/learn/event-notification-api.md
- en/docs/try-out/event-notification-api.md
This PR is to update the Event Notification API page.
This will fix https://github.com/wso2/docs-open-banking/issues/779#issuecomment-1523066711.
> Update the Event Notification API page

- en/docs/learn/consent-manager.md
- en/docs/try-out/consent-manager.md
This PR is to update consent management portal configurations.
This will fix https://github.com/wso2/docs-open-banking/issues/782.
> Update consent management portal configurations

- en/docs/learn/consent-manager.md
- en/docs/try-out/consent-manager.md
This PR is to fix a typo on the consent manager page. 
This will fix https://github.com/wso2/docs-open-banking/issues/794.
> Fix typos in consent mgr page

- en/docs/learn/consent-manager.md
- en/docs/try-out/consent-manager.md
This PR is to update consent management portal configs. 
This will fix https://github.com/wso2/docs-open-banking/issues/782#issuecomment-1539592295.
> Update consent management portal configs

- en/docs/learn/consent-manager.md
- en/docs/try-out/consent-manager.md
This PR is to update the u2 note.
Issue reference: https://github.com/wso2/docs-open-banking/issues/782
> Update u2 note

- en/docs/learn/variable-recurring-payments-configuration.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update Variable Recurring Payments configurations

- en/mkdocs.yml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update The topics in Learn tab

- en/docs/learn/api-specifications.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update API Specifications Introduction Page

- en/docs/get-started/dynamic-client-registration.md
- en/docs/get-started/quick-start-guide.md
- en/docs/get-started/set-up-toolkits.md
- en/docs/get-started/try-out-flow.md
- en/docs/install-and-setup/configuring-api-manager-for-ob.md
- en/docs/install-and-setup/configuring-identity-server-for-ob.md
- en/docs/install-and-setup/prerequisites.md
- en/docs/install-and-setup/setting-up-servers.md
- en/docs/learn/consent-manager.md
- en/docs/try-out/account-and-transaction-flow.md
- en/docs/try-out/confirmation-of-funds-flow.md
- en/docs/try-out/consent-manager.md
- en/docs/try-out/dynamic-client-registration-flow.md
- en/docs/try-out/event-notification-api.md
- en/docs/try-out/payment-initiation-flow.md
- en/docs/try-out/variable-recurring-payments-flow.md
This PR is to update the UK Toolkit documentation with APIM 4.2.0 and IS 6.0.0 compatibility.
Reference: https://github.com/wso2/docs-open-banking/issues/772
> Update doc with APIM 4.2.0 and IS 6.0.0 compatibility

- en/docs/learn/consent-manager.md
- en/docs/try-out/consent-manager.md
This PR is to update the consent manager page. This will fix https://github.com/wso2/docs-open-banking/issues/795.
> Update consent mgr page

- en/docs/index.md
- en/theme/material/main.html
This PR is to update the fonts used in the UK Toolkit doc.
This will fix https://github.com/wso2/docs-open-banking/issues/847.
> Update fonts used in UK Toolkit doc

- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/prerequisites.md
This PR is to add a note on the DB compatibility. 
This will fix https://github.com/wso2/docs-open-banking/issues/844.
> Add db compatibility note

- en/docs/get-started/set-up-toolkits.md
**description**
The IS version that require enabling adaptive authentication for JSK 17 is updated as IS 6.0.0 and above.
> Update IS version that require enabling adaptive authentication for JDK 17

- en/docs/install-and-setup/setting-up-databases.md
$subject
Ref: https://github.com/wso2/financial-open-banking/issues/42
> Link to the PR for changes to the training content in …
> Update docs with mysql connector removal

- en/docs/conformance/functional-conformance-suite.md
- en/docs/install-and-setup/configuring-api-manager-for-ob.md
- en/docs/install-and-setup/configuring-identity-server-for-ob.md
> Fixes https://github.com/wso2/docs-open-banking/issues/881
> Link to the PR for changes to the training content in …
> Modifying Idempotency related docs

- en/docs/learn/integration-with-bank.md
Add docs for core banking integration with UK API v4
https://github.com/wso2-enterprise/ob-compliance-toolkit-uk/issues/494
> …
> Update core banking integration for UK API v4

- en/docs/get-started/try-out-flow.md
- en/docs/learn/integration-with-bank.md
- en/docs/try-out/account-and-transaction-flow.md
- en/docs/try-out/confirmation-of-funds-flow.md
- en/docs/try-out/payment-initiation-flow.md
Add documentation for UK API v4
https://github.com/wso2-enterprise/ob-compliance-toolkit-uk/issues/494
> Link to the PR for …
> Add documentation for UK API v4

- en/docs/try-out/account-and-transaction-flow.md
- en/docs/try-out/confirmation-of-funds-flow.md
Fix doc formatting for UK API v4
https://github.com/wso2-enterprise/ob-compliance-toolkit-uk/issues/494
> Link to the PR for …
> Fix doc formatting for UK API v4

- en/docs/install-and-setup/configuring-identity-server-for-ob.md
Add consent expiration configuration
https://github.com/wso2-enterprise/ob-compliance-toolkit-uk/issues/634
> Link to the PR for …
> Add consent expiration configuration
